SOURCES=main.cpp Selection.cpp Sort.cpp Shell.cpp Insertion.cpp Count.cpp Node.cpp List.cpp Quick.cpp Heap.cpp InsertHeap.cpp HeapTree.cpp Merge.cpp

all: ${SOURCES}
	g++ -o prog -W -Wall -ansi -pedantic -I. ${SOURCES}

clean:
	rm -rf prog *.o
